<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>TES4ConverterCompatibility</AssemblyName>
    <RootNamespace>TES4ConverterCompatibility</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <DebugType>portable</DebugType>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup Condition="'$(PandoraApiPath)' != ''">
    <Reference Include="Pandora API">
      <HintPath>$(PandoraApiPath)</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
